#!/usr/bin/env python3
"""AccaMatrix OpenFootball expansion harvester.

Scans JSON generated by fbtxt2json from the openfootball/europe repository,
selects only configured AccaMatrix expansion leagues, normalises completed
matches + future fixtures, and writes a small feed consumed by WordPress.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import unicodedata
from pathlib import Path
from typing import Any


def norm(value: str) -> str:
    value = unicodedata.normalize("NFKD", value or "")
    value = "".join(ch for ch in value if not unicodedata.combining(ch))
    value = value.lower().replace("&", " and ")
    value = re.sub(r"[^a-z0-9]+", " ", value)
    return re.sub(r"\s+", " ", value).strip()


def phrase_in(phrase: str, haystack: str) -> bool:
    p = norm(phrase)
    h = norm(haystack)
    if not p or not h:
        return False
    return re.search(r"(?:^|\s)" + re.escape(p) + r"(?:$|\s)", h) is not None


def season_key(label: str) -> tuple[int, int]:
    s = str(label or "")
    m = re.search(r"(20\d{2})\s*[-/]\s*(\d{2,4})", s)
    if m:
        start = int(m.group(1))
        end_raw = m.group(2)
        end = int(end_raw) if len(end_raw) == 4 else (start // 100) * 100 + int(end_raw)
        if end < start:
            end += 100
        return start, end
    m = re.search(r"\b(20\d{2})\b", s)
    if m:
        year = int(m.group(1))
        return year, year
    return (0, 0)


def season_from_path(path: Path, data: dict[str, Any]) -> str:
    for part in reversed(path.parts):
        if re.fullmatch(r"20\d{2}-\d{2}", part) or re.fullmatch(r"20\d{2}", part):
            return part
    name = str(data.get("name") or "")
    m = re.search(r"(20\d{2}\s*[-/]\s*\d{2,4}|\b20\d{2}\b)", name)
    return re.sub(r"\s+", "", m.group(1)).replace("/", "-") if m else "unknown"


def score_pair(score: Any, key: str) -> tuple[int | None, int | None]:
    if not isinstance(score, dict):
        return None, None
    raw = score.get(key)
    if not isinstance(raw, (list, tuple)) or len(raw) < 2:
        return None, None
    try:
        if raw[0] is None or raw[1] is None:
            return None, None
        return int(raw[0]), int(raw[1])
    except (TypeError, ValueError):
        return None, None


def normalise_match(raw: dict[str, Any], season: str, source_file: str) -> dict[str, Any] | None:
    home = str(raw.get("team1") or raw.get("home") or raw.get("home_team") or "").strip()
    away = str(raw.get("team2") or raw.get("away") or raw.get("away_team") or "").strip()
    date = str(raw.get("date") or "").strip()
    if not home or not away or not re.fullmatch(r"\d{4}-\d{2}-\d{2}", date):
        return None

    ft_h, ft_a = score_pair(raw.get("score"), "ft")
    ht_h, ht_a = score_pair(raw.get("score"), "ht")
    status = "completed" if ft_h is not None and ft_a is not None else "scheduled"
    time = str(raw.get("time") or "").strip()
    if time:
        # Keep only HH:MM for WordPress. OpenFootball can include timezone text.
        m = re.search(r"\b(\d{1,2}:\d{2})\b", time)
        time = m.group(1).zfill(5) if m else ""

    return {
        "season": season,
        "date": date,
        "time": time,
        "home": home,
        "away": away,
        "status": status,
        "ft_home": ft_h,
        "ft_away": ft_a,
        "ht_home": ht_h,
        "ht_away": ht_a,
        "round": str(raw.get("round") or raw.get("matchday") or "").strip(),
        "source_file": source_file,
    }


def candidate_score(cfg: dict[str, Any], path: Path, data: dict[str, Any]) -> int:
    path_text = norm(str(path))
    name_text = norm(str(data.get("name") or ""))
    combined = f"{path_text} {name_text}"

    country_hits = [h for h in cfg.get("country_hints", []) if phrase_in(h, combined)]
    if not country_hits:
        return -1

    best = -1
    for alias in cfg.get("aliases", []):
        a = norm(alias)
        if not a:
            continue
        score = 0
        if phrase_in(a, name_text):
            score = 130 + len(a)
        elif phrase_in(a, path_text):
            score = 100 + len(a)
        elif a in name_text:
            score = 70 + len(a)
        elif a in path_text:
            score = 50 + len(a)
        if score > 0 and score > best:
            best = score
    return best


def load_json_files(root: Path) -> list[tuple[Path, dict[str, Any]]]:
    out: list[tuple[Path, dict[str, Any]]] = []
    for path in sorted(root.rglob("*.json")):
        try:
            data = json.loads(path.read_text(encoding="utf-8-sig"))
        except Exception:
            continue
        if isinstance(data, dict) and isinstance(data.get("matches"), list):
            out.append((path, data))
    return out


def dedupe_matches(matches: list[dict[str, Any]]) -> list[dict[str, Any]]:
    chosen: dict[str, dict[str, Any]] = {}
    for match in matches:
        key = "|".join([match["date"], norm(match["home"]), norm(match["away"])])
        old = chosen.get(key)
        if old is None:
            chosen[key] = match
            continue
        # Prefer a completed row and then a row with HT score.
        old_rank = (old["status"] == "completed", old.get("ht_home") is not None)
        new_rank = (match["status"] == "completed", match.get("ht_home") is not None)
        if new_rank > old_rank:
            chosen[key] = match
    return sorted(chosen.values(), key=lambda x: (x["date"], x.get("time") or "", x["home"], x["away"]))


def harvest_one(cfg: dict[str, Any], files: list[tuple[Path, dict[str, Any]]], history_seasons: int, today: dt.date) -> tuple[dict[str, Any], dict[str, Any] | None]:
    if not cfg.get("enabled", True):
        return ({
            "code": cfg["code"], "country": cfg["country"], "league": cfg["league"],
            "enabled": False, "health": "SKIPPED", "reason": cfg.get("skip_reason", "Disabled")
        }, None)

    candidates: list[tuple[int, Path, dict[str, Any], str]] = []
    for path, data in files:
        score = candidate_score(cfg, path, data)
        if score < 0:
            continue
        season = season_from_path(path, data)
        candidates.append((score, path, data, season))

    if not candidates:
        return ({
            "code": cfg["code"], "country": cfg["country"], "league": cfg["league"],
            "enabled": True, "health": "MISSING", "reason": "No matching OpenFootball JSON dataset found"
        }, None)

    # For each season keep the highest-scoring matching JSON file(s). Split-half files can tie,
    # so keep all files within five points of that season's best score.
    by_season: dict[str, list[tuple[int, Path, dict[str, Any]]]] = {}
    for score, path, data, season in candidates:
        by_season.setdefault(season, []).append((score, path, data))

    ordered_seasons = sorted(by_season.keys(), key=season_key, reverse=True)
    selected_seasons = ordered_seasons[: max(1, history_seasons)]
    selected_files: list[tuple[int, Path, dict[str, Any], str]] = []
    for season in selected_seasons:
        rows = by_season[season]
        best = max(x[0] for x in rows)
        for score, path, data in rows:
            if score >= best - 5:
                selected_files.append((score, path, data, season))

    matches: list[dict[str, Any]] = []
    source_files: list[str] = []
    for _, path, data, season in selected_files:
        source_files.append(str(path))
        for raw in data.get("matches", []):
            if not isinstance(raw, dict):
                continue
            match = normalise_match(raw, season, str(path))
            if match:
                matches.append(match)
    matches = dedupe_matches(matches)

    if not matches:
        return ({
            "code": cfg["code"], "country": cfg["country"], "league": cfg["league"],
            "enabled": True, "health": "MISSING", "reason": "Matching dataset contained no parseable matches",
            "source_files": source_files,
        }, None)

    completed = [m for m in matches if m["status"] == "completed"]
    future = [m for m in matches if m["status"] == "scheduled" and m["date"] >= today.isoformat()]
    latest_date = max(m["date"] for m in matches)
    latest_completed = max((m["date"] for m in completed), default="")

    health = "READY"
    reason = "Current or future match data found"
    if not future and latest_completed:
        latest_completed_date = dt.date.fromisoformat(latest_completed)
        age = (today - latest_completed_date).days
        if age > 120:
            health = "STALE"
            reason = f"Latest completed match is {age} days old and no future fixtures were found"
    elif not future and not latest_completed:
        health = "MISSING"
        reason = "No completed results or future fixtures found"

    meta = {
        "code": cfg["code"],
        "country": cfg["country"],
        "league": cfg["league"],
        "enabled": True,
        "health": health,
        "reason": reason,
        "season_type": cfg.get("season_type", "season"),
        "seasons": selected_seasons,
        "matches": len(matches),
        "completed": len(completed),
        "future_fixtures": len(future),
        "latest_date": latest_date,
        "latest_completed": latest_completed,
        "source_files": sorted(set(source_files)),
    }

    payload = {
        "schema_version": 1,
        "source": "openfootball-github",
        "source_repo": "openfootball/europe",
        "league_code": cfg["code"],
        "country": cfg["country"],
        "league": cfg["league"],
        "season_type": cfg.get("season_type", "season"),
        "health": health,
        "seasons": selected_seasons,
        "matches": matches,
    }
    return meta, payload


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", required=True)
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--today", default="")
    args = parser.parse_args()

    config_path = Path(args.config)
    input_root = Path(args.input)
    output_root = Path(args.output)
    leagues_dir = output_root / "leagues"
    leagues_dir.mkdir(parents=True, exist_ok=True)

    config = json.loads(config_path.read_text(encoding="utf-8"))
    today = dt.date.fromisoformat(args.today) if args.today else dt.datetime.now(dt.timezone.utc).date()
    history_seasons = int(config.get("history_seasons", 3))
    files = load_json_files(input_root)

    generated_at = dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    manifest_entries: list[dict[str, Any]] = []
    all_fixtures: list[dict[str, Any]] = []

    configured_codes = {str(x["code"]) for x in config.get("leagues", [])}
    for stale_file in leagues_dir.glob("*.json"):
        if stale_file.stem not in configured_codes:
            stale_file.unlink()

    for league_cfg in config.get("leagues", []):
        meta, payload = harvest_one(league_cfg, files, history_seasons, today)
        if payload is not None:
            payload["generated_at"] = generated_at
            path = leagues_dir / f"{league_cfg['code']}.json"
            path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
            meta["file"] = f"data/leagues/{league_cfg['code']}.json"

            if meta.get("health") == "READY":
                for match in payload["matches"]:
                    if match["status"] != "scheduled" or match["date"] < today.isoformat():
                        continue
                    all_fixtures.append({
                        "league_code": payload["league_code"],
                        "country": payload["country"],
                        "league": payload["league"],
                        "season_type": payload["season_type"],
                        "season": match.get("season", ""),
                        "date": match["date"],
                        "time": match.get("time", ""),
                        "home": match["home"],
                        "away": match["away"],
                    })
        else:
            old = leagues_dir / f"{league_cfg['code']}.json"
            if old.exists():
                old.unlink()
        manifest_entries.append(meta)

    manifest = {
        "schema_version": 1,
        "generated_at": generated_at,
        "source": "openfootball-github",
        "source_repo": config.get("source_repo", "openfootball/europe"),
        "history_seasons": history_seasons,
        "summary": {
            "configured": len(manifest_entries),
            "enabled": sum(1 for x in manifest_entries if x.get("enabled")),
            "ready": sum(1 for x in manifest_entries if x.get("health") == "READY"),
            "stale": sum(1 for x in manifest_entries if x.get("health") == "STALE"),
            "missing": sum(1 for x in manifest_entries if x.get("health") == "MISSING"),
            "skipped": sum(1 for x in manifest_entries if x.get("health") == "SKIPPED"),
        },
        "leagues": manifest_entries,
    }
    output_root.mkdir(parents=True, exist_ok=True)
    (output_root / "manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    all_fixtures.sort(key=lambda x: (x["date"], x.get("time") or "", x["league_code"], x["home"], x["away"]))
    fixtures_payload = {
        "schema_version": 1,
        "generated_at": generated_at,
        "source": "openfootball-github",
        "fixtures": all_fixtures,
    }
    (output_root / "fixtures.json").write_text(json.dumps(fixtures_payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    status_lines = [
        "# AccaMatrix Expansion Feed Status",
        "",
        f"Generated: **{generated_at}**",
        "",
        "| Country | League | Code | Health | Matches | Future | Latest result |",
        "|---|---|---:|---|---:|---:|---|",
    ]
    for x in manifest_entries:
        status_lines.append(
            f"| {x['country']} | {x['league']} | `{x['code']}` | **{x['health']}** | "
            f"{x.get('matches', 0)} | {x.get('future_fixtures', 0)} | {x.get('latest_completed', '—') or '—'} |"
        )
    (output_root / "STATUS.md").write_text("\n".join(status_lines) + "\n", encoding="utf-8")

    print(json.dumps(manifest["summary"], indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
